[workspace]
members = ["red4ext", "red4ext-sys", "red4ext-macros"]
exclude = ["examples"]
resolver = "2"

[workspace.package]
version = "0.5.3"
rust-version = "1.75"
edition = "2021"
license = "MIT"
authors = ["jekky"]

[profile.release]
lto = "thin"

[workspace.metadata.release]
pre-release-commit-message = "chore: release {{version}}"
tag-prefix = ""
shared-version = true
publish = false
